"""empty message

Revision ID: f214896e7d39
Revises: e686dd8ea7e9
Create Date: 2016-04-20 14:35:05.323847

"""

# revision identifiers, used by Alembic.
revision = 'f214896e7d39'
down_revision = 'e686dd8ea7e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('brief', sa.String(length=300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'brief')
    ### end Alembic commands ###
